[dev]
#common
server_address = "0.0.0.0"
server_port = 4000
retry_times = 3

#database config
db_host = ""
db_name = ""
db_collection = ""
db_username = ""
db_password = ""

#image profiles
post_image_profiles = "320,720,1080"
avatar_image_profiles = "90,160,320"

#storage aws S3 config 
region = ""
storage_url = ""
bucket_name = ""
access_key_id = ""
access_key_secret = ""

[prod]
#common
server_port = 4000
retry_times = 3

#database config
db_host = ""
db_name = ""
db_collection = ""
db_username = ""
db_password = ""

#image profiles
post_image_profiles = "320,720,1080"
avatar_image_profiles = "90,160,320"

#storage aws S3 config 
region = ""
storage_url = ""
bucket_name = ""
access_key_id = ""
access_key_secret = ""
